import 'package:flutter/material.dart';import 'package:organix/core/app_export.dart';import 'package:organix/widgets/app_bar/appbar_leading_image.dart';import 'package:organix/widgets/app_bar/appbar_title_searchview.dart';import 'package:organix/widgets/app_bar/custom_app_bar.dart';
// ignore_for_file: must_be_immutable
class AllCategoryScreen extends StatelessWidget {AllCategoryScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 24.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 17.h), child: Text("Category", style: CustomTextStyles.titleLargeSemiBold))), SizedBox(height: 25.v), _buildVegetables(context), SizedBox(height: 16.v), _buildMeat(context), SizedBox(height: 17.v), _buildBottelbigOne(context), SizedBox(height: 17.v), _buildBeverages(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 96.v, leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 20.h, top: 17.v, bottom: 15.v), onTap: () {onTapIconlyLightOu(context);}), title: AppbarTitleSearchview(margin: EdgeInsets.only(left: 21.h), hintText: "Search your needs here...", controller: searchController)); } 
/// Section Widget
Widget _buildVegetables(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 10.h, right: 18.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 131.v, width: 114.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 7.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 14.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 83.v), Text("Vegetables", style: CustomTextStyles.labelLargeBlack900)]))), CustomImageView(imagePath: ImageConstant.imgBasketFullVegetables, height: 81.v, width: 114.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 3.v))])), Container(margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.symmetric(horizontal: 1.h, vertical: 14.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgColorfulFruits, height: 60.v, width: 97.h), SizedBox(height: 22.v), Text("Fruits", style: CustomTextStyles.labelLargeBlack900), SizedBox(height: 2.v)])), Container(margin: EdgeInsets.only(left: 17.h), padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 15.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), CustomImageView(imagePath: ImageConstant.imgNutsWalnutPea, height: 57.v, width: 93.h), SizedBox(height: 21.v), Text("Dry Fruits", style: CustomTextStyles.labelLargeBlack900)]))])); } 
/// Section Widget
Widget _buildMeat(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 11.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 132.v, width: 112.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 6.h), padding: EdgeInsets.symmetric(horizontal: 34.h, vertical: 16.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 80.v), Text("Meat", style: CustomTextStyles.labelLargeBlack900)]))), CustomImageView(imagePath: ImageConstant.imgWholeChickenS, height: 75.v, width: 112.h, alignment: Alignment.topCenter)])), Container(margin: EdgeInsets.only(left: 11.h, top: 1.v), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 4.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgRipplePreDustTea250g, height: 80.adaptSize, width: 80.adaptSize), SizedBox(height: 12.v), Text("Tea/ Coffee", style: CustomTextStyles.labelLargeBlack900), SizedBox(height: 12.v)])), Container(height: 131.v, width: 134.h, margin: EdgeInsets.only(left: 1.h, top: 1.v), child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 79.v), Text("Oil & Ghee", style: CustomTextStyles.labelLargeBlack900)]))), CustomImageView(imagePath: ImageConstant.imgOil1, height: 88.v, width: 134.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 2.v))]))])); } 
/// Section Widget
Widget _buildBottelbigOne(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 17.h, right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(padding: EdgeInsets.all(6.h), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgBottelbig1, height: 81.v, width: 40.h), SizedBox(height: 9.v), Text("Diary Products", style: CustomTextStyles.labelLargeBlack900), SizedBox(height: 10.v)])), Container(margin: EdgeInsets.only(left: 17.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 14.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSpices1, height: 66.v, width: 59.h), SizedBox(height: 16.v), Text("Spices", style: CustomTextStyles.labelLargeBlack900), SizedBox(height: 2.v)])), Container(height: 131.v, width: 115.h, margin: EdgeInsets.only(left: 18.h), child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.centerLeft, child: Container(padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 17.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 77.v), Text("Rice", style: CustomTextStyles.labelLargeBlack900)]))), CustomImageView(imagePath: ImageConstant.imgRicebag1, height: 69.v, width: 104.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 18.v))]))])); } 
/// Section Widget
Widget _buildBeverages(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 131.v, width: 104.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 2.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 8.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 95.v), Text("Beverages", style: CustomTextStyles.labelLargeBlack900)]))), CustomImageView(imagePath: ImageConstant.imgBottle1, height: 68.v, width: 104.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 8.v))])), Container(margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 17.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgBiscits1, height: 59.v, width: 86.h), SizedBox(height: 19.v), Text("Biscuits", style: CustomTextStyles.labelLargeBlack900)])), Container(margin: EdgeInsets.only(left: 17.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 7.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgVillainHydraP, height: 73.v, width: 61.h), SizedBox(height: 15.v), Text("Deodorants", style: CustomTextStyles.labelLargeBlack900), SizedBox(height: 10.v)]))])); } 
/// Navigates to the homeOneContainerScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeOneContainerScreen); } 
 }
