import 'package:flutter/material.dart';import 'package:organix/core/app_export.dart';import 'package:organix/widgets/app_bar/appbar_leading_image.dart';import 'package:organix/widgets/app_bar/appbar_subtitle.dart';import 'package:organix/widgets/app_bar/custom_app_bar.dart';import 'package:organix/widgets/custom_elevated_button.dart';import 'package:organix/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class PaymentFinalScreen extends StatelessWidget {PaymentFinalScreen({Key? key}) : super(key: key);

TextEditingController deliveryController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 35.v), decoration: AppDecoration.fillGray, child: Column(children: [Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary, child: Text("Cash on Delivery", style: CustomTextStyles.bodyLarge16)), SizedBox(height: 10.v), _buildDelivery(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildConfirm(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 23.h, top: 43.v, bottom: 24.v)), centerTitle: true, title: AppbarSubtitle(text: "Payment", margin: EdgeInsets.only(top: 44.v, bottom: 16.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildDelivery(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 10.v), decoration: AppDecoration.fillOnPrimary, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("Subtotal", style: CustomTextStyles.bodySmall12)), SizedBox(height: 18.v, width: 45.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.centerRight, child: Text("30.00", style: CustomTextStyles.bodySmall12)), CustomImageView(imagePath: ImageConstant.imgCurrencyRupee, height: 14.adaptSize, width: 14.adaptSize, alignment: Alignment.centerLeft)]))])), SizedBox(height: 6.v), SizedBox(height: 30.v, width: 336.h, child: Stack(alignment: Alignment.topRight, children: [CustomTextFormField(width: 335.h, controller: deliveryController, hintText: "Delivery", textInputAction: TextInputAction.done, alignment: Alignment.center, borderDecoration: TextFormFieldStyleHelper.underLineLightGreen), Align(alignment: Alignment.topRight, child: Text("Free", style: CustomTextStyles.bodySmallPrimary12))])), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 26.v, width: 81.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Text("Grand  Total", style: CustomTextStyles.labelLargeBlack900SemiBold)), Align(alignment: Alignment.bottomCenter, child: Text("Inclusive of All Taxes", style: CustomTextStyles.bodySmall8))])), Container(height: 18.v, width: 46.h, margin: EdgeInsets.only(bottom: 8.v), child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.centerRight, child: Text("30.00", style: CustomTextStyles.labelLargeBlack900SemiBold)), CustomImageView(imagePath: ImageConstant.imgCurrencyRupee, height: 14.adaptSize, width: 14.adaptSize, alignment: Alignment.centerLeft)]))])), SizedBox(height: 2.v)])); } 
/// Section Widget
Widget _buildConfirm(BuildContext context) { return Container(margin: EdgeInsets.only(left: 110.h, right: 110.h, bottom: 11.v), decoration: AppDecoration.outlineLightgreen100, child: CustomElevatedButton(text: "Confirm", buttonStyle: CustomButtonStyles.outlineBlack, buttonTextStyle: CustomTextStyles.titleLargeOnPrimarySemiBold, onPressed: () {onTapConfirm(context);})); } 
/// Navigates to the paymentPopupScreen when the action is triggered.
onTapConfirm(BuildContext context) { Navigator.pushNamed(context, AppRoutes.paymentPopupScreen); } 
 }
