import 'package:flutter/material.dart';import 'package:organix/core/app_export.dart';import 'package:organix/widgets/app_bar/appbar_leading_image.dart';import 'package:organix/widgets/app_bar/appbar_subtitle.dart';import 'package:organix/widgets/app_bar/custom_app_bar.dart';class MyCartProductOneScreen extends StatelessWidget {const MyCartProductOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 70.v), decoration: AppDecoration.fillGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 35.v), _buildTomatoesOne(context), Spacer(), _buildItemInVegetable(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 23.h, top: 43.v, bottom: 24.v)), centerTitle: true, title: AppbarSubtitle(text: "Vegetable", margin: EdgeInsets.only(top: 44.v, bottom: 16.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildTomatoesOne(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 8.v), decoration: AppDecoration.fillOnPrimary, child: Column(children: [Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTomatoes1, height: 43.v, width: 59.h, margin: EdgeInsets.only(top: 14.v)), Padding(padding: EdgeInsets.only(left: 11.h, top: 7.v, bottom: 31.v), child: Text("Fresh Organic Tomato \r500g", style: CustomTextStyles.bodySmall12)), Spacer(), CustomImageView(imagePath: ImageConstant.imgLocation, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 31.v))])), SizedBox(height: 5.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 70.h, right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 18.v, width: 45.h, margin: EdgeInsets.only(top: 3.v, bottom: 5.v), child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.centerRight, child: Text("30.00", style: CustomTextStyles.labelLargeBlack900)), CustomImageView(imagePath: ImageConstant.imgCurrencyRupee, height: 14.adaptSize, width: 14.adaptSize, alignment: Alignment.centerLeft)])), SizedBox(height: 27.v, width: 74.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Container(height: 24.v, width: 23.h, decoration: BoxDecoration(color: appTheme.blueGray100, border: Border.all(color: appTheme.gray50001, width: 1.h))))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Row(children: [GestureDetector(onTap: () {onTapThirteen(context);}, child: SizedBox(height: 27.v, width: 25.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(height: 22.v, width: 25.h, decoration: BoxDecoration(color: theme.colorScheme.onPrimary))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 7.h), child: Text("-", style: theme.textTheme.bodyLarge)))]))), Padding(padding: EdgeInsets.only(left: 9.h, top: 2.v), child: Text("1", style: CustomTextStyles.bodyLarge16)), Padding(padding: EdgeInsets.only(left: 15.h), child: Text("+", style: theme.textTheme.bodyLarge))])))]))]))), SizedBox(height: 10.v)])); } 
/// Section Widget
Widget _buildItemInVegetable(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 14.v), decoration: AppDecoration.fillOnPrimary, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 10.v), child: Text("1 item in vegetable", style: CustomTextStyles.bodyMediumGray50001)), Container(height: 27.v, width: 69.h, margin: EdgeInsets.only(bottom: 8.v), child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.centerRight, child: Text("30.00", style: CustomTextStyles.titleMediumSemiBold18)), CustomImageView(imagePath: ImageConstant.imgCurrencyRupee, height: 21.v, width: 22.h, alignment: Alignment.centerLeft)]))])); } 
/// Navigates to the myCartProductScreen when the action is triggered.
onTapThirteen(BuildContext context) { Navigator.pushNamed(context, AppRoutes.myCartProductScreen); } 
 }
