import 'package:flutter/material.dart';import 'package:organix/core/app_export.dart';import 'package:organix/presentation/home_one_page/home_one_page.dart';import 'package:organix/presentation/my_cart_page/my_cart_page.dart';import 'package:organix/widgets/custom_bottom_bar.dart';
// ignore_for_file: must_be_immutable
class ProfileScreen extends StatelessWidget {ProfileScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray100, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 40.v), child: Column(children: [_buildSetting(context), SizedBox(height: 42.v), _buildClock(context), SizedBox(height: 13.v), _buildNounTracking(context), SizedBox(height: 12.v), _buildLocation(context), SizedBox(height: 11.v), _buildCalling(context), SizedBox(height: 14.v), _buildSetting1(context), SizedBox(height: 51.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgUpload, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 3.v)), GestureDetector(onTap: () {onTapTxtLogout(context);}, child: Padding(padding: EdgeInsets.only(left: 8.h), child: Text("Logout ", style: CustomTextStyles.bodyLarge16)))]))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildSetting(BuildContext context) { return Container(width: 335.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 13.v), decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [Align(alignment: Alignment.centerRight, child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse35, height: 84.adaptSize, width: 84.adaptSize, radius: BorderRadius.circular(42.h), margin: EdgeInsets.only(top: 15.v)), CustomImageView(imagePath: ImageConstant.imgSetting, height: 25.adaptSize, width: 25.adaptSize, margin: EdgeInsets.only(left: 88.h, bottom: 74.v), onTap: () {onTapImgSetting(context);})])), SizedBox(height: 11.v), Text("Will Johnson", style: CustomTextStyles.headlineSmallBlack900), SizedBox(height: 1.v), Text("+91 8632148965", style: CustomTextStyles.bodySmall12), SizedBox(height: 39.v)])); } 
/// Section Widget
Widget _buildClock(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgClock, height: 22.v, width: 23.h, margin: EdgeInsets.only(bottom: 5.v)), Padding(padding: EdgeInsets.only(left: 11.h, bottom: 2.v), child: Text("My Orders", style: CustomTextStyles.bodyLarge16)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlack900, height: 26.adaptSize, width: 26.adaptSize)])); } 
/// Section Widget
Widget _buildNounTracking(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgNounTracking3477608, height: 28.adaptSize, width: 28.adaptSize, margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 7.h, bottom: 6.v), child: Text("Track Order", style: CustomTextStyles.bodyLarge16)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlack900, height: 26.adaptSize, width: 26.adaptSize, margin: EdgeInsets.only(top: 5.v))])); } 
/// Section Widget
Widget _buildLocation(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgLocationPrimary19x19, height: 19.adaptSize, width: 19.adaptSize, margin: EdgeInsets.only(bottom: 8.v)), Padding(padding: EdgeInsets.only(left: 13.h, bottom: 4.v), child: Text("Address", style: CustomTextStyles.bodyLarge16)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlack900, height: 26.adaptSize, width: 26.adaptSize, margin: EdgeInsets.only(top: 2.v))])); } 
/// Section Widget
Widget _buildCalling(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgCalling, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 9.v)), Padding(padding: EdgeInsets.only(left: 13.h, bottom: 3.v), child: Text("Contact Us", style: CustomTextStyles.bodyLarge16)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlack900, height: 26.adaptSize, width: 26.adaptSize)])); } 
/// Section Widget
Widget _buildSetting1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSettingPrimary, height: 19.adaptSize, width: 19.adaptSize, margin: EdgeInsets.only(bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 9.h, bottom: 2.v), child: Text("Settings", style: CustomTextStyles.bodyLarge16)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlack900, height: 26.adaptSize, width: 26.adaptSize)])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homeOnePage; case BottomBarEnum.Iconlylightoutlinebag: return AppRoutes.myCartPage; case BottomBarEnum.Heart: return "/"; case BottomBarEnum.Profile: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homeOnePage: return HomeOnePage(); case AppRoutes.myCartPage: return MyCartPage(); default: return DefaultWidget();} } 
/// Navigates to the profileSettingScreen when the action is triggered.
onTapImgSetting(BuildContext context) { Navigator.pushNamed(context, AppRoutes.profileSettingScreen); } 
/// Navigates to the loginScreen when the action is triggered.
onTapTxtLogout(BuildContext context) { Navigator.pushNamed(context, AppRoutes.loginScreen); } 
 }
